kind: Service
apiVersion: v1
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
  - name: mongo-express
    protocol: TCP
    port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: run
                      operator: In
                      values:
                      - mongo-express
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 90
      containers:
      - name: mongo-express
        image: mongo-express:0.49
        imagePullPolicy: Always
        env:
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "true"
          - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            value: admin
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: password
        envFrom:
        - secretRef:
            name: mongo-express-credentials
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 200m
            memory: 300Mi
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8081
